### ISSUE TITLE
[New Metadata Schema Request]: Library Minimal Metadata

### ISSUE THREAD

**Issue by hongna2008** [brain-bican/metadata-schemas#28]
### Contact Details

na.hong@yale.edu; Wenjin.J.Zheng@uth.tmc.edu

### Schema Name

Library Minimal Metadata

### Oranizational Usage

Library generation labs, sequencing cores, and archives of BICAN (BRAIN Initiative Cell Atlas Network) community.

### General Description

To harmonize gaps among existing library construction processes, the Library Minimal Metadata (LMM) was developed through the consensus of domain experts, including biomedical researchers, experimenters, data analysts, and informaticians. LMM is a metadata standard that aims to facilitate the interoperation and reuse of essential information and enhance the value of library-related resources.

### What format are you submitting your schema in?

.xlsx or .csv or .tsv

### Completed README

- [X] I have completed a README for this schema.

**Comment by hongna2008** [comment]
[Library_Minimal_Metadata_Latesd_Version.xlsx](https://github.com/brain-bican/metadata-schemas/files/12566125/Library_Minimal_Metadata_Latesd_Version.xlsx)

[Library_Minimal_Metadata_Latesd_Version_09212023.xlsx](https://github.com/brain-bican/metadata-schemas/files/12690062/Library_Minimal_Metadata_Latesd_Version_09212023.xlsx)

[Library_Minimal_Metadata_Latesd_Version_final.xlsx](https://github.com/brain-bican/metadata-schemas/files/13211503/Library_Minimal_Metadata_Latesd_Version_final.xlsx)

**Comment by patrick-lloyd-ray** [comment]
@rightbower, would you be able to take a look at this with @mgiglio99 and @patrick-lloyd-ray
