### ISSUE TITLE
New Metadata Schema Request: Marmoset Metadata

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [brain-bican/metadata-schemas#46]
### Contact Details

patrick.ray@alleninstitute.org

### Schema Name

Marmoset Metadata

### Oranizational Usage

BICAN, HMBA

### General Description

This is a metadata schema that describes the HMBA marmoset population and spatial omics. The sheet is separated into HMBA marmoset population and HMBA marmoset spatial omics to reflect the data. 
[HMBA Marmoset Population.xlsx](https://github.com/user-attachments/files/16074213/HMBA.Marmoset.Population.xlsx)
[HMBA Marmoset Omics Spatial Population.xlsx](https://github.com/user-attachments/files/16074215/HMBA.Marmoset.Omics.Spatial.Population.xlsx)

### Suggested Reviewers

@djarecka @nsuvarnaiari @rightbower

### What format are you submitting your schema in?

.xlsx or .csv or .tsv

### Completed README

- [x] I have completed a README for this schema.

**Comment by patrick-lloyd-ray** [comment]
For Population:

- [x]  align names and labels
- [x] check for existing fields
- [x] assign UUIDs to existing fields
- [x] assign UUIDs to new fields
- [x] add version
- [x] add date
- [x] complete data_type
- [x] complete is_required column
- [ ] add permissible values
- [x] update README

**Comment by patrick-lloyd-ray** [comment]
For spatial omics population:

- [x] align names and labels
- [x] check for existing fields
- [x] assign UUIDs to existing fields
- [x] assign UUIDs to new fields
- [x] add version
- [x] add date
- [x] complete data_type
- [x] complete is_required column
- [ ] add permissible values
- [x] update README

**Comment by patrick-lloyd-ray** [comment]
@djarecka @nsuvarnaiari @rightbower 

Would you be able to discuss progress at the WG meeting next week?

**Comment by nsuvarnaiari** [comment]
Hi @patrick-lloyd-ray 

I haven't looked at the files yet. Though planned to do it last week. I am not sure if I will get a chance to look at them before WG call. Sorry for not being proactive.

Thanks,
Suvvi

**Comment by patrick-lloyd-ray** [comment]
No worries! We can discuss this one at a later meeting.

**Comment by djarecka** [comment]
@patrick-lloyd-ray - perhaps I got confused, you want us to review the xlsx files or #51?

**Comment by patrick-lloyd-ray** [comment]
> @patrick-lloyd-ray - perhaps I got confused, you want us to review the xlsx files or #51?

The csv files in #51 and the xlsx files here contain the same information. Those on #51 are formatted in our standard format, but there is some information that needs completion by the reviewers here before we can mark this as ready for acceptance. (see tasks in the comments above)

**Comment by djarecka** [comment]
ok, got it. I looked at the PR, and it was really incomplete, so I would prefer to wait for the additional information to review it again and discuss.

**Comment by patrick-lloyd-ray** [comment]
> ok, got it. I looked at the PR, and it was really incomplete, so I would prefer to wait for the additional information to review it again and discuss.

This is all the information we have, unfortunately. Would you like me to review it for you?

**Comment by djarecka** [comment]
> > ok, got it. I looked at the PR, and it was really incomplete, so I would prefer to wait for the additional information to review it again and discuss.
> 
> This is all the information we have, unfortunately. Would you like me to review it for you?

I did review what I found and left my comments/questions in #51 last week.

**Comment by patrick-lloyd-ray** [comment]
> I did review what I found and left my comments/questions in #51 last week.

Not the PR, but the schema itself (standardizing the fields and aligning it with existing schemas).

**Comment by djarecka** [comment]
> > I did review what I found and left my comments/questions in #51 last week.
> 
> Not the PR, but the schema itself (standardizing the fields and aligning it with existing schemas).

I'm sorry, it looks like I misunderstood the task at the end... Haven't had time this week, but happy to clarify today during the meeting
