### ISSUE TITLE
New Metadata Schema Request: Developing human, NHP, tissue metadata

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [brain-bican/metadata-schemas#47]
### Contact Details

patrick.ray@alleninstitute.org

### Schema Name

Developing human, NHP, and tissue metadata

### Oranizational Usage

BICAN, HMBA

### General Description

This is a metadata schema that describes the data for developing human, developing non-human primate, and general tissue metadata for developing life cycle stages.
[Dev NHP.xlsx](https://github.com/user-attachments/files/16075409/Dev.NHP.xlsx)
[Dev Human.xlsx](https://github.com/user-attachments/files/16075410/Dev.Human.xlsx)
[Dev Tissue.xlsx](https://github.com/user-attachments/files/16075411/Dev.Tissue.xlsx)

### Suggested Reviewers

@licongcui @MariahKenney @patrick-lloyd-ray

### What format are you submitting your schema in?

.xlsx or .csv or .tsv

### Completed README

- [x] I have completed a README for this schema.

**Comment by patrick-lloyd-ray** [comment]
For Human:

- [x] align names and labels
- [x] check for existing fields
- [x] assign UUIDs to existing fields
- [x] assign UUIDs to new fields
- [x] add version
- [x] add date
- [x] complete data_type
- [x] complete is_required column
- [ ] add permissible values
- [x] update README

**Comment by patrick-lloyd-ray** [comment]
For NHP:

- [x] align names and labels
- [x] check for existing fields
- [x] assign UUIDs to existing fields
- [x] assign UUIDs to new fields
- [x] add version
- [x] add date
- [x] complete data_type
- [x] complete is_required column
- [ ] add permissible values
- [x] update README

**Comment by patrick-lloyd-ray** [comment]
For Dev Tissue:

- [x] align names and labels
- [x] check for existing fields
- [x] assign UUIDs to existing fields
- [x] assign UUIDs to new fields
- [x] add version
- [x] add date
- [x] complete data_type
- [x] complete is_required column
- [ ] add permissible values
- [x] update README

**Comment by patrick-lloyd-ray** [comment]
@licongcui @MariahKenney 

Would you be able to take a look this week so that we can discuss at the WG meeting next week?

**Comment by patrick-lloyd-ray** [comment]
I added definitions to the terms in these sheets. I will also complete the remaining tasks (save the README for after WG approval). Are there any objections here? @licongcui @MariahKenney

**Comment by patrick-lloyd-ray** [comment]
We will discuss this in the WG tomorrow. The permissible values will need discussion with the larger group.

**Comment by patrick-lloyd-ray** [comment]
Awaiting feedback on the definitions from WG. However, @licongcui and @MariahKenney it is ready for a final look from you. I will try to merge this soon. 

@puja-trivedi and @djarecka would you like to make sure the model generator works as expected for these tables?

**Comment by djarecka** [comment]
> @puja-trivedi and @djarecka would you like to make sure the model generator works as expected for these tables?

yes, we will check it early enxt week

**Comment by patrick-lloyd-ray** [comment]
> > @puja-trivedi and @djarecka would you like to make sure the model generator works as expected for these tables?
> 
> yes, we will check it early enxt week

Fantastic! Thank you!

**Comment by djarecka** [comment]
@patrick-lloyd-ray - I've created the google sheet that I used to create a first version of the model: https://docs.google.com/spreadsheets/d/1UCkvjIDlgfr7i_6WkI8t7ktLC-p3McGD4tYmSy2snSI/edit?usp=sharing

I had to add a couple of things to automatically convert types (e.g., from `test` to `string`), but the most important thing is that I need information about the classes and permissable values
